### ISSUE TITLE
Make Add first task more visible and easy for new desktop users

### ISSUE THREAD

**Issue by EdwardMuturi** [joelkanyi/FocusBloom#114]
When a new user launches the app on desktop, their home page only has description text and an icon. The description directs the user how to add the task but no easy and direct click action is attached to the words. The user has to click the navigation icon instead.

The suggested solution is to add an `Add Your First Task` button that navigates the user to the Add task page. Please suggestion edit on attached picture.
<img width="1123" alt="Screenshot 2024-06-04 at 18 35 20" src="https://github.com/joelkanyi/FocusBloom/assets/9773206/f525d73a-4cc8-4df4-b746-c9c90400810c">

**Comment by joelkanyi** [comment]
This makes sense, will implement in the next release
