### ISSUE TITLE
Are there plans to update to compose-multiplatform 1.7.0 and further?

### ISSUE THREAD

**Issue by javac9** [joelkanyi/FocusBloom#140]
Are there plans to update to compose-multiplatform 1.7.0 and further? I really like the app and would like to see that happen.

**Comment by joelkanyi** [comment]
Hey @javac9 

Yes, will update CMP  to [1.7.0-beta02](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.7.0-beta02)

**Comment by joelkanyi** [comment]
This done now
