### ISSUE TITLE
Are there plans to replace Voyager navigation and ViewModel with native libraries?

### ISSUE THREAD

**Issue by javac9** [joelkanyi/FocusBloom#141]
Hello, I really like what you made there, many kudos!

However, IMHO it would be even better if you replace Voyager navigation and view-model with native ones because those aren't going away, unlike a 3rd-party library that eventually might stop being maintained.

Looking forward to hearing your opinion on this.

**Comment by joelkanyi** [comment]
Migration completed, test it and let me know
