### ISSUE TITLE
Edit Task: From Calendar Screen

### ISSUE THREAD

**Issue by CarlosTaipe** [JoelKanyi/FocusBloom#48]
Hi @JoelKanyi , I'm installed the app from google play and I can't edit my task, however, in the last update your mentioned this functionality

**Comment by JoelKanyi** [comment]
Hey @CarlosTaipe I can edit tasks from my end

https://github.com/JoelKanyi/FocusBloom/assets/50293753/a0080c47-2b55-45ca-b1fa-3a832d6f0c4c

**Comment by CarlosTaipe** [comment]
Hey @JoelKanyi, I will like can edit my task to the next day, example. I created task "Excercise" for tomorrow but I ned change the hour, now I can't do this, for this reason I created this issue.   


![photo_5008381585027869701_y](https://github.com/JoelKanyi/FocusBloom/assets/50587898/3b7fe94e-4c36-4b58-ae3c-43cbc0812209)

**Comment by JoelKanyi** [comment]
Okay noted, let me reedit the title of your issue

**Comment by JoelKanyi** [comment]
Edit options have been added
