### ISSUE TITLE
Font related exception thrown on desktop

### ISSUE THREAD

**Issue by garthgilmourni** [JoelKanyi/FocusBloom#66]
When I try to launch the desktop version of the application the following exception is thrown:

` java.lang.IllegalStateException: Can't load font from font/montserrat_bold.ttf`

Looking at the codebase there is an expected `font` function, which on the JVM looks for the TTF file in a font subdirectory of the resources folder. I don't believe this is being populated.

**Comment by JoelKanyi** [comment]
Hey @garthgilmourni how are launching the desktop app?

Are you using this command on your terminal: `./gradlew :desktop:run`

**Comment by JoelKanyi** [comment]
You are welcome
